### ISSUE TITLE
是否可以通过名字自动转换UID识别信息呢？

### ISSUE THREAD

**Issue by Nenot233** [Ikaros-521/nonebot_plugin_searchBiliInfo#1]

**Comment by Ikaros-521** [comment]
目前我这是构思了3套方案：

1. 使用**原始方案**，自定义name和uid数组，name添加用户需要快捷查询的昵称 对应的uid填写此昵称对应的用户uid（需要用户自己修改部分源码）
2. 使用**vtbs.moe**的所有主播信息接口获取信息存入本地当数据检索。这个方案需要用户查询时输入完整的正确的名称 且 需要查询的用户在此表中。
3. 调用**b站官方API**接口进行用户查询。这个方案需要用户**配置cookie**，且用户搜索对关键词、粉丝数等对检索结果都有影响，且搜索出的用户信息较多，默认第一个结果，意味着用户也基本上是需要完整昵称匹配才行。

**Comment by Ikaros-521** [comment]
如果你这边的查询对象并不多的话，我建议是使用方案1，你可以直接写着，我给你更新，或者我告诉你怎么更新。
如果对数据需求比较大的话，可以临时先采用下方案2来本地匹配，可以很方便的扩容用户名查询的匹配量。
最后的方案三可能也会出，不过cookie这个逃不了追加

**Comment by Nenot233** [comment]
https://danmaku.suki.club/
https://megghysdanmaku.apifox.cn/api-36693842
或者可以看看这个，第二个是文档里面也有一些其他数据可以参考参考（更新建议）

**Comment by Ikaros-521** [comment]
> https://danmaku.suki.club/ https://megghysdanmaku.apifox.cn/api-36693842 或者可以看看这个，第二个是文档里面也有一些其他数据可以参考参考（更新建议）
https://github.com/Ikaros-521/LX_Bot 已经集成了，只不过我把这个小功能单独分出来了

**Comment by Ikaros-521** [comment]
v0.1.0版本更新，方案二+三功能实现，已上传更新
