### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by Nenot233** [Ikaros-521/nonebot_plugin_searchBiliInfo#10]
![image](https://github.com/Ikaros-521/nonebot_plugin_searchBiliInfo/assets/108965579/d07098eb-6720-456d-8088-a4c515562f8d)
https://danmakus.com/search
这一项目可以查查看

**Comment by Ikaros-521** [comment]
> ![image](https://github.com/Ikaros-521/nonebot_plugin_searchBiliInfo/assets/108965579/d07098eb-6720-456d-8088-a4c515562f8d)
> https://danmakus.com/search
> 这一项目可以查查看

我记得有做过拆分的功能，到时候看看吧 😌

**Comment by Ikaros-521** [comment]
v1.7.7 新增 dmk分析
