### ISSUE TITLE
danmakus的API更新为v2了，原来的API寄了喵

### ISSUE THREAD

**Issue by zhx79513** [Ikaros-521/nonebot_plugin_searchBiliInfo#11]
![图片](https://github.com/Ikaros-521/nonebot_plugin_searchBiliInfo/assets/5063357/7f3d2c63-6e08-4aad-bdec-38e3576edbc2)

https://github.com/Ikaros-521/nonebot_plugin_searchBiliInfo/blob/57da7037c4b04e47b1d5ee8b503284483f567062/nonebot_plugin_searchBiliInfo/__init__.py#L537-L542

v2 API：
https://ukamnads.icu/swagger/index.html

**Comment by Ikaros-521** [comment]
接口改过去了，不过还是v1的，v2再说吧0.0

**Comment by Ikaros-521** [comment]
好家伙 原来都3周了，都没发现0.0
