### ISSUE TITLE
dmk lap都寄了

### ISSUE THREAD

**Issue by Nenot233** [Ikaros-521/nonebot_plugin_searchBiliInfo#13]

**Comment by Ikaros-521** [comment]
让我鉴定鉴定

**Comment by Ikaros-521** [comment]
恢复兼容 [https://github.com/Ikaros-521/nonebot_plugin_searchBiliInfo/commit/e9a9e8a2f86efe1cc31b8be144192e530f3f7644](https://github.com/Ikaros-521/nonebot_plugin_searchBiliInfo/commit/e9a9e8a2f86efe1cc31b8be144192e530f3f7644)
