### ISSUE TITLE
月榜寄了

### ISSUE THREAD

**Issue by liuzj288** [Ikaros-521/nonebot_plugin_searchBiliInfo#14]
![image](https://github.com/Ikaros-521/nonebot_plugin_searchBiliInfo/assets/13833404/3473724d-d07f-4266-83e9-bf05f82eb409)

**Comment by Ikaros-521** [comment]
![image](https://github.com/Ikaros-521/nonebot_plugin_searchBiliInfo/assets/40910637/77d940e3-c759-4f3b-a97e-3cb95269e614)
官方关闭了月榜接口了
