### ISSUE TITLE
查营收数据营收价格出错，相差一位数

### ISSUE THREAD

**Issue by Nenot233** [Ikaros-521/nonebot_plugin_searchBiliInfo#4]
当月ZAZ营收75.6万，但是出来的图是756.89万

**Comment by Nenot233** [comment]
751行修改一下就行
            out_str += '| ' + name + ' | ' + str(mid) + ' | '
            if income > 1000000:
                income = round(income / 10000000, 2)
                out_str += str(income) + '万 | '

**Comment by Ikaros-521** [comment]
> 751行修改一下就行 out_str += '| ' + name + ' | ' + str(mid) + ' | ' if income > 1000000: income = round(income / 10000000, 2) out_str += str(income) + '万 | '

确实。应该是接口变了，追加一个0可以解决，下一版本更新

**Comment by Ikaros-521** [comment]
v1.3.10 已更新
