### ISSUE TITLE
没有匹配command_start的设置，只响应/开头命令

### ISSUE THREAD

**Issue by liuzj288** [Ikaros-521/nonebot_plugin_searchBiliInfo#5]
匹配下就可以了

**Comment by Ikaros-521** [comment]
> 匹配下就可以了

因为做的 keyword捕获，之后会改成 command。预期下一版本升级

**Comment by Ikaros-521** [comment]
v1.4.0 已升级，on_command

**Comment by liuzj288** [comment]
> v1.4.0 已升级，on_command

一次只能查一个id吗？能不能支持一个命令同时查多个id

**Comment by Ikaros-521** [comment]
> > v1.4.0 已升级，on_command
> 
> 一次只能查一个id吗？能不能支持一个命令同时查多个id

呃 /查 命令倒是可以一次性查询多个，其他的不太行，虽然可以做，但是命令会变得很麻烦 ，用起来很繁琐
