### ISSUE TITLE
营收似乎超时了

### ISSUE THREAD

**Issue by Nenot233** [Ikaros-521/nonebot_plugin_searchBiliInfo#6]
查营收的接口改了吗？

**Comment by Ikaros-521** [comment]
确实，vtbs.fun 站点挂彩了

**Comment by Nenot233** [comment]
![image](https://user-images.githubusercontent.com/108965579/215242129-8949245e-762e-4feb-bbe5-528e7cbdf06b.png)

**Comment by Nenot233** [comment]
http://www.vtbs.fun/ranking/growIndex

**Comment by Ikaros-521** [comment]
> http://www.vtbs.fun/ranking/growIndex

哦豁 回头看看更新更新

**Comment by Nenot233** [comment]
https://vtbs.moe/live
搭配的api文档
https://github.com/dd-center/vtbs.moe/blob/master/api.md

**Comment by Ikaros-521** [comment]
> https://vtbs.moe/live 搭配的api文档 https://github.com/dd-center/vtbs.moe/blob/master/api.md

moe接口给到的功能感觉差点意思

**Comment by Nenot233** [comment]
https://vup.loveava.top/ranking

**Comment by Ikaros-521** [comment]
> https://vup.loveava.top/ranking

你可以发送命令 /vtb网站 
emmm

**Comment by Nenot233** [comment]
https://[biligank](https://biligank.com/about).com/about

**Comment by Ikaros-521** [comment]
站点很多 但是需要经常查的感觉并没有这么多

**Comment by Nenot233** [comment]
呸发多了

**Comment by Ikaros-521** [comment]
不过确实有打算把biligank的接口做上看看 能不能玩出点花

**Comment by Nenot233** [comment]
可以做集成化的查弹幕（所有uid）和查礼物（金额总和）
![92289fc64219ce3d71c00905ddc31dc](https://user-images.githubusercontent.com/108965579/215250529-1da33414-1d52-4b01-883f-857658cff2c4.jpg)
![40d6607c7c9393899c619675568c12f](https://user-images.githubusercontent.com/108965579/215250533-389bf776-b7f8-4c0c-a8fc-07fb6f3619bc.png)

**Comment by Ikaros-521** [comment]
> 可以做集成化的查弹幕（所有uid）和查礼物（金额总和） ![92289fc64219ce3d71c00905ddc31dc](https://user-images.githubusercontent.com/108965579/215250529-1da33414-1d52-4b01-883f-857658cff2c4.jpg) ![40d6607c7c9393899c619675568c12f](https://user-images.githubusercontent.com/108965579/215250533-389bf776-b7f8-4c0c-a8fc-07fb6f3619bc.png)

看吧 有接口的话最好，其实最开始就想做这种类似查成分的功能，不过没看到好用的接口

**Comment by Nenot233** [comment]
总和一下就有了，这个也不是一个接口做出来的

**Comment by Ikaros-521** [comment]
> 总和一下就有了，这个也不是一个接口做出来的

呀嘞呀嘞deze 那你做吧www 做好pr 就靠你了
