### ISSUE TITLE
更新了data以后 我发现我的1G内存 跑不动了

### ISSUE THREAD

**Issue by milo1023** [Ikaros-521/nonebot_plugin_searchBiliInfo#7]
数据太大 内存不够 nb 无法启动

**Comment by Ikaros-521** [comment]
> 数据太大 内存不够 nb 无法启动

！对哦 这样的话 就把data.py删减到自定义昵称吧
本来昵称查询本地数据也就是辅助作用。

`DATA=[{"mid": 697091119, "uname": "猫雷", "roomid": 0}]`

**Comment by Ikaros-521** [comment]
> 数据太大 内存不够 nb 无法启动

等会我发个版，把data删空好了

**Comment by Ikaros-521** [comment]
v1.5.5 已更新

**Comment by milo1023** [comment]
好滴 感谢大佬回复

**Comment by Ikaros-521** [comment]
> 好滴 感谢大佬回复
![GXGK_YOUB~}V9_ APT9Y@9E](https://user-images.githubusercontent.com/40910637/219843278-58b924a3-dc29-41f4-b83c-bfb3e312b557.jpg)
