### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Nenot233** [Ikaros-521/nonebot_plugin_searchBiliInfo#8]
https://laplace.live/user/【uid】

**Comment by Ikaros-521** [comment]
套个截图，不过速度应该很慢
![N(X9HGBPRS6FAV6D(X%V ~9](https://user-images.githubusercontent.com/40910637/220548516-28f3fc46-18b4-4f4b-98dc-6c3a27048431.gif)

**Comment by Nenot233** [comment]
截图可能会显示不出
![image](https://user-images.githubusercontent.com/108965579/220549398-f51280f9-cfef-424d-9383-2ec1f9a26a98.png)

**Comment by Nenot233** [comment]
截图可能会显示不出
![image](https://user-images.githubusercontent.com/108965579/220549519-716c6fcd-88f5-4ae2-94dc-689cdb177a4f.png)

**Comment by Ikaros-521** [comment]
> 截图可能会显示不出 ![image](https://user-images.githubusercontent.com/108965579/220549519-716c6fcd-88f5-4ae2-94dc-689cdb177a4f.png)

确实，没办法。不想上playwright

**Comment by Ikaros-521** [comment]
试了下 htmlrender封装的比我想象的要好， 效果还行，等会发版试试

**Comment by Ikaros-521** [comment]
更新1.5.8
![laplace_user](https://user-images.githubusercontent.com/40910637/220557896-36f0b519-447a-4a4b-845e-55ad3d73acc7.png)

**Comment by Nenot233** [comment]
https://zeroroku.com/bilibili/author/【uid】

**Comment by Nenot233** [comment]
优化lap查用户建议：触发指令添加回复，正在查询，请稍后

**Comment by Ikaros-521** [comment]
> 优化lap查用户建议：触发指令添加回复，正在查询，请稍后

v1.5.10 优化

**Comment by Ikaros-521** [comment]
> [https://zeroroku.com/bilibili/author/【uid】](https://zeroroku.com/bilibili/author/%E3%80%90uid%E3%80%91)

v1.5.11

**Comment by mas-alone** [comment]
```
playwright._impl._api_types.Error: net::ERR_CONNECTION_TIMED_OUT at https://laplace.live/user/10086
=========================== logs ===========================
navigating to "https://laplace.live/user/10086", waiting until "networkidle"
============================================================
```

lap站点提示连接不上，但本地访问网站正常，偶尔可以查询到..

**Comment by Ikaros-521** [comment]
> ```
> playwright._impl._api_types.Error: net::ERR_CONNECTION_TIMED_OUT at https://laplace.live/user/10086
> =========================== logs ===========================
> navigating to "https://laplace.live/user/10086", waiting until "networkidle"
> ============================================================
> ```
> 
> lap站点提示连接不上，但本地访问网站正常，偶尔可以查询到..

正常，这几天lap传播有点广，我看他现在服务器有点吃不消。
不过确实会有超时问题，如果愿意等的话，可以延长页面加载超时时长。或者缩短直接重发查询。

**Comment by Nenot233** [comment]
![image](https://user-images.githubusercontent.com/108965579/220829442-ced6b87c-f2ad-4704-afbf-7aa434f2737e.png)
多半是

**Comment by mas-alone** [comment]
> > ```
> > playwright._impl._api_types.Error: net::ERR_CONNECTION_TIMED_OUT at https://laplace.live/user/10086
> > =========================== logs ===========================
> > navigating to "https://laplace.live/user/10086", waiting until "networkidle"
> > ============================================================
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > lap站点提示连接不上，但本地访问网站正常，偶尔可以查询到..
> 
> 正常，这几天lap传播有点广，我看他现在服务器有点吃不消。 不过确实会有超时问题，如果愿意等的话，可以延长页面加载超时时长。或者缩短直接重发查询。

感谢答复!明白了

**Comment by Ikaros-521** [comment]
小水管要挤爆了
![220548516-28f3fc46-18b4-4f4b-98dc-6c3a27048431](https://user-images.githubusercontent.com/40910637/220829565-1a1ebfc9-254d-476e-a6ac-a43fd0f20a73.gif)

**Comment by Nenot233** [comment]
![image](https://user-images.githubusercontent.com/108965579/222958819-d156eaca-e4a6-4820-9fde-44dd666b61ca.png)
会考虑这些功能增加吗

**Comment by Nenot233** [comment]
https://vtbs.moe/live

**Comment by Ikaros-521** [comment]
感觉用处不大，不过加上也问题不大
![TUD~V_ `BTEOO`G_5PFVQSK](https://user-images.githubusercontent.com/40910637/222958936-e2f4940b-97ad-4e47-97bc-9376afeb3b8a.jpg)

**Comment by Ikaros-521** [comment]
> 

v1.6.3

**Comment by Nenot233** [comment]
https://stats.nailv.live/about
赛博斗虫

**Comment by Ikaros-521** [comment]
> https://stats.nailv.live/about 赛博斗虫

有点东西

**Comment by Ikaros-521** [comment]
> https://stats.nailv.live/about 赛博斗虫

v1.6.9 测试发行

**Comment by Nenot233** [comment]
指令/查
是否可以再加一个B站空间推送
例如：
用户名：XXX
UID:XXX
房间号：XXX
粉丝数：XXX
舰团数：XXX

链接分享XXX的个人空间or个人空间的链接

**Comment by Ikaros-521** [comment]
> 指令/查 是否可以再加一个B站空间推送 例如： 用户名：XXX UID:XXX 房间号：XXX 粉丝数：XXX 舰团数：XXX
> 
> 链接分享XXX的个人空间or个人空间的链接

干脆把直播间一起推送上去得了
![TUD~V_ `BTEOO`G_5PFVQSK](https://user-images.githubusercontent.com/40910637/230854080-666b9cbd-2dbc-43f5-bb72-c86a682bea90.jpg)

**Comment by Nenot233** [comment]
> > 指令/查 是否可以再加一个B站空间推送 例如： 用户名：XXX UID：XXX 房间号：XXX 粉丝数：XXX 舰团数：XXX
> > 链接分享XXX的个人空间或个人空间的链接
> 
> 干脆把直播间一起推送上去得了 ![啪~V_ BTEOOG_5PFVQSK](https://user-images.githubusercontent.com/40910637/230854080-666b9cbd-2dbc-43f5-bb72-c86a682bea90.jpg)

你是天才！

**Comment by Ikaros-521** [comment]
![~%8M9E( )2VP95KR )DTU](https://user-images.githubusercontent.com/40910637/230870772-423791ac-71f9-4b1e-8bfc-d653e3029839.jpg)
