### ISSUE TITLE
可以加入获取完整关注列表和粉丝牌的方法吗

### ISSUE THREAD

**Issue by qqyc** [Ikaros-521/nonebot_plugin_searchBiliInfo#9]
参考这个油猴脚本
https://greasyfork.org/zh-CN/scripts/451485-gd-slime%E7%9A%84bilibili%E7%BB%88%E6%9E%81%E6%88%90%E5%88%86%E6%8C%87%E7%A4%BA%E5%99%A8/code

**Comment by Ikaros-521** [comment]
回头看看

**Comment by Ikaros-521** [comment]
虽然但是 他调用的也是官方的API，也没法获取完整的关注和牌子，锁了的更不行
![image](https://user-images.githubusercontent.com/40910637/221105643-52a418bc-524f-43a9-ace3-157f69b1166a.png)
